#!/bin/sh
# Runs repeated full and incremental fragment-mode qualification against the current
# committed revision using the local binary. Docker is deliberately not involved.
set -eu

RUNS="${DOCIFY_QUALIFICATION_RUNS:-3}"
OUTPUT_ROOT="${DOCIFY_QUALIFICATION_OUTPUT:-fragment-qualification}"

case "$RUNS" in
    ''|*[!0-9]*|0)
        echo "DOCIFY_QUALIFICATION_RUNS must be a positive integer" >&2
        exit 2
        ;;
esac
if [ -z "${DOCIFY_LLM_BASE_URL:-}" ] || [ -z "${DOCIFY_LLM_API_KEY:-}" ] || [ -z "${DOCIFY_LLM_MODEL:-}" ]; then
    echo "DOCIFY_LLM_BASE_URL, DOCIFY_LLM_API_KEY, and DOCIFY_LLM_MODEL are required" >&2
    exit 2
fi

ROOT="$(git rev-parse --show-toplevel)"
case "$OUTPUT_ROOT" in
    /*) ;;
    *) OUTPUT_ROOT="$ROOT/$OUTPUT_ROOT" ;;
esac
RUN_ID="$(date -u +%Y%m%dT%H%M%SZ)-$$"
ARTIFACTS="$OUTPUT_ROOT/$RUN_ID"
TEMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/docify-fragments.XXXXXX")"
WORKTREE="$TEMP_ROOT/repository"
BINARY="$TEMP_ROOT/docify-repo"
WORKTREE_ADDED=0

cleanup() {
    if [ "$WORKTREE_ADDED" -eq 1 ]; then
        git -C "$ROOT" worktree remove --force "$WORKTREE" >/dev/null 2>&1 || true
    fi
    rm -rf "$TEMP_ROOT"
}
trap cleanup EXIT HUP INT TERM

snapshot_output() {
    destination="$1"
    cp -R "$WORKTREE" "$destination"
    rm -f "$destination/.git"
}

mkdir -p "$ARTIFACTS"
git -C "$ROOT" worktree add --detach "$WORKTREE" HEAD >/dev/null
WORKTREE_ADDED=1
go -C "$WORKTREE" build -o "$BINARY" ./cmd/docify-repo

run=1
while [ "$run" -le "$RUNS" ]; do
    run_dir="$ARTIFACTS/run-$run"
    full_report=".docify/qualification-full-$run.json"
    incremental_report=".docify/qualification-incremental-$run.json"
    mkdir -p "$run_dir"

    (
        cd "$WORKTREE"
        unset DOCIFY_BASE_SHA DOCIFY_HEAD_SHA DOCIFY_DOCS_DIR DOCIFY_STATE_PATH DOCIFY_REPORT_PATH DOCIFY_PUBLISHER
        export DOCIFY_GENERATION_STRATEGY=fragments
        "$BINARY" sync --full --publisher worktree --output json --report "$full_report"
    ) > "$run_dir/full-result.json"
    cp "$WORKTREE/$full_report" "$run_dir/full-report.json"
    rm "$WORKTREE/$full_report"
    snapshot_output "$run_dir/repository-snapshot"

    (
        cd "$WORKTREE"
        unset DOCIFY_BASE_SHA DOCIFY_HEAD_SHA DOCIFY_DOCS_DIR DOCIFY_STATE_PATH DOCIFY_REPORT_PATH DOCIFY_PUBLISHER
        export DOCIFY_GENERATION_STRATEGY=fragments
        "$BINARY" sync --publisher worktree --output json --report "$incremental_report"
    ) > "$run_dir/incremental-result.json"
    cp "$WORKTREE/$incremental_report" "$run_dir/incremental-report.json"
    rm "$WORKTREE/$incremental_report"
    if ! grep -q '"status":"noop"' "$run_dir/incremental-result.json"; then
        echo "incremental qualification run $run was not a no-op" >&2
        exit 1
    fi

    if [ "$run" -gt 1 ]; then
        if ! diff -ru "$ARTIFACTS/run-1/repository-snapshot" "$run_dir/repository-snapshot" > "$run_dir/repository.diff"; then
            echo "fragment qualification run $run produced different generated bytes" >&2
            exit 1
        fi
    fi
    echo "completed fragment qualification run $run/$RUNS"
    run=$((run + 1))
done

printf 'qualification artifacts: %s\n' "$ARTIFACTS"
