package usecase

import (
	"context"
	"errors"
	"reflect"
	"strings"
	"testing"

	documentationmodel "docify-repo/internal/app/documentation/model"
	sharedmodel "docify-repo/internal/model"
)

func TestClassifyRole(t *testing.T) {
	tests := []struct {
		path    string
		content string
		role    sharedmodel.SourceRole
	}{
		{path: "cmd/server/main.go", role: sharedmodel.RoleProductionSource},
		{path: "api/service.proto", role: sharedmodel.RoleContract},
		{path: "migrations/001.sql", role: sharedmodel.RoleDatabase},
		{path: ".github/workflows/ci.yml", role: sharedmodel.RoleRuntimeConfiguration},
		{path: "package.json", role: sharedmodel.RoleDependencyManifest},
		{path: "src/server_test.go", role: sharedmodel.RoleTest},
		{path: "src/generated/client.go", role: sharedmodel.RoleGeneratedCode},
		{path: "fixtures/response.json", role: sharedmodel.RoleFixture},
		{path: "go.sum", role: sharedmodel.RoleLockFile},
		{path: "README.md", role: sharedmodel.RoleProse},
		{path: "source.unknown", role: sharedmodel.RoleUnknownSource},
		{path: "web/styles.css", role: sharedmodel.RoleProductionSource},
		{path: "requirements-dev.txt", role: sharedmodel.RoleDependencyManifest},
		{path: "tool", content: "#!/usr/bin/env python3\n", role: sharedmodel.RoleProductionSource},
		{path: "generated.go", content: "// Code generated by tool. DO NOT EDIT.\n", role: sharedmodel.RoleGeneratedCode},
	}

	for _, test := range tests {
		t.Run(test.path, func(t *testing.T) {
			role, _ := classifyRole(test.path, []byte(test.content), nil)
			if role != test.role {
				t.Fatalf("classifyRole() = %q, want %q", role, test.role)
			}
		})
	}
}

func TestClassifyRoleUsesFirstOverride(t *testing.T) {
	overrides := []documentationmodel.RoleOverride{
		{Pattern: "features/**", Role: sharedmodel.RoleContract},
		{Pattern: "**/*.feature", Role: sharedmodel.RoleTest},
	}
	role, reason := classifyRole("features/payment.feature", nil, overrides)
	if role != sharedmodel.RoleContract || reason != "role_override" {
		t.Fatalf("classifyRole() = %q, %q, want contract override", role, reason)
	}
}

func TestPlanScansAndClassifiesWithoutReadingDeniedPaths(t *testing.T) {
	entries := []sharedmodel.TrackedEntry{
		{Path: "vendor/dependency.go", Mode: "100644"},
		{Path: "main_test.go", Mode: "100644"},
		{Path: "docs/generated/index.md", Mode: "100644"},
		{Path: "large.go", Mode: "100644"},
		{Path: "main.go", Mode: "100644"},
		{Path: ".env", Mode: "100644"},
		{Path: "README.md", Mode: "100644"},
		{Path: "image.bin", Mode: "100644"},
	}
	worktree := &fakeWorktree{contents: map[string]sharedmodel.FileContent{
		"main.go":      textContent("main.go", "package main\n"),
		"main_test.go": textContent("main_test.go", "package main\n"),
		"README.md":    textContent("README.md", "# Repository\n"),
		"image.bin":    textContent("image.bin", "\x00binary"),
		"large.go":     {Path: "large.go", Size: 1000, Data: []byte("package"), Truncated: true},
	}}
	application := New(&fakeGitSource{root: "/repository", entries: entries}, worktree, &fakeState{result: sharedmodel.StateLoadResult{Missing: true}}, nil, nil)

	result, err := application.Plan(context.Background(), testPlanInput())
	if err != nil {
		t.Fatalf("Plan() error = %v", err)
	}
	if result.TrackedPaths != 8 || result.IncludedPaths != 3 || result.TriggeringPaths != 1 || result.ExcludedPaths != 5 {
		t.Errorf("result counts = %+v, want tracked=8 included=3 triggering=1 excluded=5", result)
	}
	wantReads := []string{"README.md", "image.bin", "large.go", "main.go", "main_test.go"}
	if !reflect.DeepEqual(worktree.reads, wantReads) {
		t.Errorf("read paths = %v, want %v", worktree.reads, wantReads)
	}
	if !sortDecisions(result.Files) {
		t.Errorf("decisions are not sorted: %+v", result.Files)
	}
	decision := decisionByPath(t, result.Files, ".env")
	if decision.Role != sharedmodel.RoleSecret || decision.Reason != "secret_filename" {
		t.Errorf("secret decision = %+v", decision)
	}
}

func TestPlanRejectsHighConfidenceSecretWithoutExposingValue(t *testing.T) {
	secret := "AKIA1234567890ABCDEF"
	worktree := &fakeWorktree{contents: map[string]sharedmodel.FileContent{
		"main.go": textContent("main.go", "package main\nconst token = \""+secret+"\"\n"),
	}}
	application := New(&fakeGitSource{root: "/repository", entries: []sharedmodel.TrackedEntry{{Path: "main.go", Mode: "100644"}}}, worktree, &fakeState{result: sharedmodel.StateLoadResult{Missing: true}}, nil, nil)

	_, err := application.Plan(context.Background(), testPlanInput())
	if err == nil || !strings.Contains(err.Error(), "high-confidence secret value") {
		t.Fatalf("Plan() error = %v, want secret detection error", err)
	}
	if strings.Contains(err.Error(), secret) {
		t.Fatal("secret value appeared in error")
	}
}

func TestSecretPathCannotBeOverriddenOrRead(t *testing.T) {
	policy := testSourcePolicy()
	policy.RoleOverrides = []documentationmodel.RoleOverride{{Pattern: ".env", Role: sharedmodel.RoleProductionSource}}
	worktree := &fakeWorktree{}
	application := New(&fakeGitSource{root: "/repository", entries: []sharedmodel.TrackedEntry{{Path: ".env", Mode: "100644"}}}, worktree, &fakeState{result: sharedmodel.StateLoadResult{Missing: true}}, nil, nil)

	input := testPlanInput()
	input.SourcePolicy = policy
	result, err := application.Plan(context.Background(), input)
	if err != nil {
		t.Fatalf("Plan() error = %v", err)
	}
	if len(worktree.reads) != 0 {
		t.Fatalf("read paths = %v, secret path must not be read", worktree.reads)
	}
	decision := decisionByPath(t, result.Files, ".env")
	if decision.Role != sharedmodel.RoleSecret || decision.IncludedAsContext {
		t.Fatalf("decision = %+v, want denied secret", decision)
	}
}

func TestSecretDetectorAvoidsShortTokenPrefix(t *testing.T) {
	if containsHighConfidenceSecret([]byte("example: AKIA1234")) {
		t.Fatal("containsHighConfidenceSecret() = true for short placeholder")
	}
}

func TestValidateSourcePolicyRejectsSecretRoleOverride(t *testing.T) {
	policy := testSourcePolicy()
	policy.RoleOverrides = []documentationmodel.RoleOverride{{Pattern: "**/*", Role: sharedmodel.RoleSecret}}
	if err := validateSourcePolicy(policy); err == nil {
		t.Fatal("validateSourcePolicy() error = nil, want unsupported override error")
	}
}

func TestPlanPropagatesContextCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	application := New(&fakeGitSource{err: context.Canceled}, &fakeWorktree{}, &fakeState{}, nil, nil)
	_, err := application.Plan(ctx, testPlanInput())
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("Plan() error = %v, want context cancellation", err)
	}
}

type fakeGitSource struct {
	root    string
	entries []sharedmodel.TrackedEntry
	err     error
}

func (f *fakeGitSource) RepositoryRoot(context.Context) (string, error) {
	if f.err != nil {
		return "", f.err
	}
	return f.root, nil
}

func (f *fakeGitSource) ListWorktreeTracked(context.Context) ([]sharedmodel.TrackedEntry, error) {
	return append([]sharedmodel.TrackedEntry(nil), f.entries...), f.err
}

func (f *fakeGitSource) ListTree(context.Context, string) ([]sharedmodel.TrackedEntry, error) {
	return append([]sharedmodel.TrackedEntry(nil), f.entries...), f.err
}

func (f *fakeGitSource) ReadBlob(context.Context, string, int64) (sharedmodel.FileContent, error) {
	return sharedmodel.FileContent{}, f.err
}

func (f *fakeGitSource) RevisionExists(context.Context, string) (bool, error) {
	return f.err == nil, f.err
}

func (f *fakeGitSource) Changes(context.Context, string, string) ([]sharedmodel.RawChange, error) {
	return nil, f.err
}

type fakeWorktree struct {
	contents map[string]sharedmodel.FileContent
	reads    []string
}

type fakeState struct {
	result sharedmodel.StateLoadResult
	err    error
}

func (f *fakeState) Load(context.Context, string, string) (sharedmodel.StateLoadResult, error) {
	return f.result, f.err
}

func (f *fakeState) Decode(context.Context, []byte) (sharedmodel.StateLoadResult, error) {
	return f.result, f.err
}

func (f *fakeWorktree) ReadTracked(_ context.Context, _, repositoryPath string, _ int64) (sharedmodel.FileContent, error) {
	f.reads = append(f.reads, repositoryPath)
	content, exists := f.contents[repositoryPath]
	if !exists {
		return sharedmodel.FileContent{}, errors.New("unexpected read")
	}
	return content, nil
}

func testSourcePolicy() documentationmodel.SourcePolicy {
	return documentationmodel.SourcePolicy{
		DocsDir:      "docs/generated",
		StatePath:    ".docify/state.json",
		Include:      []string{"**/*"},
		Exclude:      []string{"vendor/**"},
		MaxFileBytes: 100,
		Tests:        documentationmodel.SourceBehavior{IncludeAsContext: true},
	}
}

func testPlanInput() documentationmodel.PlanInput {
	return documentationmodel.PlanInput{
		SourcePolicy: testSourcePolicy(),
		ComponentPolicy: documentationmodel.ComponentPolicy{
			Strategy: "inferred", MaxContextBytes: 1000, MaxBatchBytes: 500,
			MaxSupportingBytes: 200, MaxManifestBytes: 200, MaxDiffBytes: 200, MaxRequestBytes: 200_000,
		},
		GenerationPolicy: documentationmodel.GenerationPolicy{
			Profile: "codebase-summary", Audience: "mixed", Mermaid: true, Provider: "openai-compatible",
			APIMode: "chat_completions", MaxOutputTokens: 1024, StructuredOutputMode: "auto",
		},
	}
}

func textContent(repositoryPath, content string) sharedmodel.FileContent {
	return sharedmodel.FileContent{Path: repositoryPath, Data: []byte(content), Size: int64(len(content))}
}

func decisionByPath(t *testing.T, decisions []sharedmodel.SourceDecision, repositoryPath string) sharedmodel.SourceDecision {
	t.Helper()
	for _, decision := range decisions {
		if decision.Path == repositoryPath {
			return decision
		}
	}
	t.Fatalf("decision for %q not found", repositoryPath)
	return sharedmodel.SourceDecision{}
}

func sortDecisions(decisions []sharedmodel.SourceDecision) bool {
	for index := 1; index < len(decisions); index++ {
		if decisions[index-1].Path > decisions[index].Path {
			return false
		}
	}
	return true
}
